apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:curtiscacti/infra.git  # your repo
    targetRevision: main                        # branch to track
    path: platform/argocd                        # path to Helm chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true     # deletes resources removed from Git
      selfHeal: true  # automatically fixes drift
